In [1]:
a = 12

In [2]:
a

12

In [3]:
b = float(a)
b

12.0

In [4]:
type(a)

int

In [5]:
#operator

In [6]:
a = 30 
b = 6

In [7]:
a+b

36

In [8]:
a-b

24

In [9]:
a*b

180

In [10]:
a=b

In [11]:
a == b #compairing L.H.S with R.H.S

True

In [13]:
a * 2

12

In [14]:
a ** 2 # power

36

In [17]:
a = 3
a += 3
a

6

In [18]:
b = 4 

In [27]:
b += 4
b

24

In [31]:
b

24

In [42]:
c = 5


In [46]:
c+=5
c

25

In [47]:
d =2

In [48]:
d += 2


In [51]:
d

4

In [53]:
e = 6
e += 6
e

12

In [54]:
f = 2

In [56]:
f += 2
f

6

In [74]:
a = [ 1,2,3,4,5]
3 in a

True

In [58]:
30 in a

False

In [59]:
a is 3

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
C:\Users\ashut\AppData\Local\Temp\ipykernel_5268\1363630279.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  a is 3


False

In [60]:
a is 5

False

In [61]:
a != 3

True

In [62]:
a == 3

False

In [63]:
a == 12

False

In [64]:
b = [1,2,3,4]

In [65]:
b is 3

False

In [66]:
b is 33

False

In [67]:
b is 23

False

In [68]:
b is 1

False

In [69]:
b is 12

False

In [88]:
c=[11,12,13,14,17]
12 in c

True

In [89]:
a = [ 1,2,3,4,5]
3 in a

True

In [90]:
b = [1,2,3,4,5]
3 in b

True

In [91]:
12 is b

False

In [92]:
b is 12

False

In [93]:
b is 1

False

In [94]:
1 is b

False

In [95]:
12 in b

False

In [96]:
11 in b 

False

In [97]:
4 in b 

True

In [98]:
b != 3

True

In [99]:
b != 11

True

In [108]:
a = int(input("enter number"))

enter number 2


In [109]:
a

2

In [110]:
a = "hello"
a

'hello'

In [113]:
a1 = "hello hdbu bhebx ej"


In [114]:
a1.capitalize()

'Hello hdbu bhebx ej'

In [115]:
a1.title()

'Hello Hdbu Bhebx Ej'

In [116]:
a1.lower()

'hello hdbu bhebx ej'

In [117]:
a1.upper()

'HELLO HDBU BHEBX EJ'

In [118]:
a2 = "919987685"

In [119]:
a2.startswith("91")

True

In [120]:
a3 = "pani@gamil.com"
a3.endswith("gmail.com")

False

In [121]:
a4 = "vxuvxq"
a4.isalnum()

True

In [124]:
words = [
    "apple",
    "application",
    "banana",
    "apricot",
    "grape",
    "pineapple",
    "appetizer",
    "orange",
    "appstore",
    "watermelon"
]
for word in words:
    if word.startswith("a"):
        print(word)

apple
application
apricot
appetizer
appstore


In [125]:
for word in words:
    if word.endswith("e"):
        print(word)

apple
grape
pineapple
orange
appstore


In [1]:
#nunmpy


In [2]:
import numpy as np 

In [4]:
a1 = np. array([11])
a1

array([11])

In [5]:
a2 = np.array([11,22,33,44])
a2


array([11, 22, 33, 44])

In [6]:
a2.ndim # number of dimensions.

1

In [7]:
a2.shape # number of rows and column.

(4,)

In [8]:
a2.size # number of elements.

4

In [9]:
#dimension

In [13]:
a1 = np.array([[[1,2,3]]])b
a1.ndim

3

In [14]:
#[ ]---- represent the dimension part (its one dimension).

In [16]:
a1 = np.array([[[1,2,3]]])
a1

array([[[1, 2, 3]]])

In [17]:
a1.shape

(1, 1, 3)

In [18]:
a1.size

3

In [19]:
#Different ways to creating numpy array

In [21]:
a1 = np.arange(22)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [22]:
a2 = np.arange(1,10,2.5) #(strat, end , jump)
a2

array([1. , 3.5, 6. , 8.5])

In [23]:
a3 = np.ones(2)
a3

array([1., 1.])

In [24]:
a4 = np.zeros(3)
a4

array([0., 0., 0.])

In [26]:
a5 = np.ones((2,3))
a5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a6 = np.identity(3) 
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
a6.shape

(3, 3)

In [37]:
a7 = np.random.random(3)#pass the input as tuple. 
a7

array([0.85946631, 0.76935213, 0.39507792])

In [41]:
a8 = np.random.rand(2) #pass the input as arrrgument.
a8

array([0.8440307 , 0.58298434])

In [42]:
# matrix  

In [43]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [2,3],
    [5,4]
])

In [46]:
result = np.matmul(a,b)
result

array([[12, 11],
       [26, 25]])

In [47]:
result = a@b

In [48]:
result

array([[12, 11],
       [26, 25]])

In [49]:
a+b

array([[3, 5],
       [8, 8]])

In [50]:
a-b

array([[-1, -1],
       [-2,  0]])

In [51]:
a/b

array([[0.5       , 0.66666667],
       [0.6       , 1.        ]])

In [53]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [54]:
np.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

  # indexing and slicing 

In [56]:
a1 = np.arange(12,24,2)
a1

array([12, 14, 16, 18, 20, 22])

In [57]:
a1[0] # +ve start with 0

np.int64(12)

In [58]:
a1[-1] #-ve start with -1(end)

np.int64(22)

In [59]:
a1[1:-1]

array([14, 16, 18, 20])

In [60]:
a2 = np.arange(24).reshape(6,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
a2[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
a2[2:-1,2:]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [76]:
 a3 = np.arange(36).reshape(6,6)
 a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [99]:
a3[1:4:2,1:4:2]

array([[ 7,  9],
       [19, 21]])

In [103]:
a3[1:4:2,-3::-2]

array([[ 9,  7],
       [21, 19]])